import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'data/local/traveller.dart';
import 'env.dart';
import 'routes.dart';

late Box<Traveller> travellerBox;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();

  // Register Adapter (generated by build_runner)
  Hive.registerAdapter(TravellerAdapter());

  // Open the box (table)
  travellerBox = await Hive.openBox<Traveller>('travellers');

  // --- DEBUG: PRINT DATABASE CONTENTS ON STARTUP ---
  debugPrint('================= LOCAL DATABASE CONTENTS =================');
  if (travellerBox.isEmpty) {
    debugPrint('Database is empty.');
  } else {
    for (var i = 0; i < travellerBox.length; i++) {
      final t = travellerBox.getAt(i);
      if (t != null) {
        debugPrint(
          'Entry #$i: Name: ${t.name}, Age: ${t.age}, Email: ${t.email}',
        );
      }
    }
  }
  debugPrint('===========================================================');
  // -------------------------------------------------

  runApp(const TravellerAIApp());
}

class TravellerAIApp extends StatelessWidget {
  const TravellerAIApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Traveller AI (${AppEnv.environment})',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.indigo),
      initialRoute: Routes.splash,
      routes: Routes.all,
    );
  }
}
